name: arvisaqi
description: A Flutter application for air quality monitoring and visualization.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.6
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  fl_chart: ^0.63.0
  geolocator: ^10.0.0
  google_maps_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  geocoding: ^2.0.5
  flutter_map: ^4.0.0
  latlong2: ^0.8.1  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/arvislogo.png
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png
    - assets/images/apple_icon.png
    - assets/images/globe_illustration.png
    - assets/images/location_illustration.png
    - assets/images/notification_illustration.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - .env
    